# Generated by Django 5.0.1 on 2024-01-27 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_verified',
        ),
    ]
