# Generated by Django 5.0.1 on 2024-01-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_person_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='about_me',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
