# Generated by Django 5.0.1 on 2024-02-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_person_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='about_me',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='درباره من'),
        ),
    ]
