# Generated by Django 5.0.1 on 2024-01-31 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_contactinfo_person_contact_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='contact_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
