# Generated by Django 5.0.1 on 2024-01-25 12:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=40), default=[], size=None),
        ),
    ]
