# Generated by Django 5.0.1 on 2024-01-25 12:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blog_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=40), default=list, size=None),
        ),
    ]
