# Generated by Django 5.0.1 on 2024-01-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='keywords',
        ),
    ]
