# Generated by Django 5.0.1 on 2024-02-26 08:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='عنوان پادکست')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=50, null=True, verbose_name='درباره پادکست')),
                ('content', models.TextField(verbose_name='توضیحات')),
                ('file', models.FileField(upload_to='podcasts/audio')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='podcasts/images/')),
                ('creators', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
