# Generated by Django 5.0.1 on 2024-02-26 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='creators',
            new_name='hosts',
        ),
    ]
