# Generated by Django 5.0.1 on 2024-02-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_alter_podcast_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='file',
            field=models.URLField(blank=True, db_index=True, default='', max_length=128, unique=True, verbose_name='لینک پادکست'),
            preserve_default=False,
        ),
    ]
