# Generated by Django 5.0.1 on 2024-02-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0004_alter_podcast_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='description',
            field=models.CharField(max_length=250, null=True, verbose_name='درباره پادکست'),
        ),
    ]
