# Generated by Django 5.0.1 on 2024-02-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='body',
            field=models.TextField(verbose_name='متن پیام'),
        ),
    ]
