# Generated by Django 5.0.1 on 2024-02-01 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام پروژه')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=150, unique=True)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='project_images/')),
                ('website_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام وبسایت')),
                ('technologies', models.CharField(blank=True, max_length=50, null=True, verbose_name='تکنولوژی های استفاده شده')),
                ('deadline', models.CharField(blank=True, max_length=50, null=True, verbose_name='مدت زمان اتمام پروژه')),
                ('domain', models.CharField(blank=True, max_length=20, null=True, verbose_name='دامنه')),
                ('creators', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='project.project')),
            ],
        ),
    ]
