# Generated by Django 5.0.1 on 2024-02-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_image_projectimage_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='domain',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='دامنه'),
        ),
    ]
