# Generated by Django 5.0.1 on 2024-02-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تکنولوژی های استفاده شده'),
        ),
    ]
