# Generated by Django 5.0.1 on 2024-02-10 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 2, 10, 18, 29, 43, 800767, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
