# Generated by Django 5.0.1 on 2024-02-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_related_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام گروه پروژه')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='related_projects',
        ),
    ]
