# Generated by Django 5.0.1 on 2024-02-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='content',
        ),
    ]
