# Generated by Django 5.0.1 on 2024-02-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_rename_description_project_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='', verbose_name='درباره پروژه'),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(default='', verbose_name='جزئیات پروژه'),
        ),
    ]
