# Generated by Django 5.0.1 on 2024-02-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_project_description_alter_project_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(default='', verbose_name='درباره پروژه'),
        ),
    ]
